### ISSUE TITLE
Gitlab CI build has failed since last Friday (2020-10-24)

### ISSUE THREAD

**Issue by mickeylam** [react-native-community/docker-android#103]
"react-native": "0.61.2"
"realm": "^6.0.4"
![image](https://user-images.githubusercontent.com/56904502/97769089-fc62a400-1b62-11eb-96a8-feacb0caff5a.png)

**Comment by gengjiawen** [comment]
Possibly due to https://github.com/react-native-community/docker-android/commit/1b7e96b20948e07672728848c22acd9fac68a1cc, I have reverted it and publish a new version.

Should fix it.

**Comment by gengjiawen** [comment]
Publish action: https://github.com/react-native-community/docker-android/runs/1335460012?check_suite_focus=true.

**Comment by dulmandakh** [comment]
we include NDK 20, not 21.

**Comment by mickeylam** [comment]
> we include NDK 20, not 21.

I see. But I did not set the NDK version in my gradle. 

Just curious, what is the default ndk version if I did not set it ?

The Gitlab CI issue is fixed now.

**Comment by gengjiawen** [comment]
> > we include NDK 20, not 21.
> 
> I see. But I did not set the NDK version in my gradle.
> 
> Just curious, what is the default ndk version if I did not set it ?
> 
> The Gitlab CI issue is fixed now.

https://github.com/react-native-community/docker-android/blob/94cf73730f9e1bbddfdb4745ab9dffc0c643b95c/Dockerfile#L12

**Comment by dulmandakh** [comment]
@mickeylam Android Gradle Plugin 4.x requires NDK 21 by default.

**Comment by ortonomy** [comment]
My CI build is also failing. How can I fix this? I have a raw react native project. I haven't specified any plugins or gradle configs.
