### ISSUE TITLE
Add Fastlane to separate Dockerfile

### ISSUE THREAD

**Issue by avegrv** [react-native-community/docker-android#114]
I would like to suggest add [Fastlane](https://github.com/fastlane/fastlane) support.

Nowadays Fastlane is a popular tool for the distribution of Apk/ISO files and other CI/CD tasks.

We can extend or create a new Dockerfile with Fastlane support.

Also, I already have a repository for building react-native apps with Fastlane 
https://github.com/avegrv/react-native-docker

**Comment by gengjiawen** [comment]
You can easily integrate with current docker. Introduce too much tools can easily make this image bloated.

```docker
FROM reactnativecommunity/react-native-android
RUN gem install fastlane
```

**Comment by avegrv** [comment]
@gengjiawen In your approach, I need to install Fastlane every time when I start a CI job, it can slow down the time of execution.

**Comment by gengjiawen** [comment]
> @gengjiawen In your approach, I need to install Fastlane every time when I start a CI job, it can slow down the time of execution.

Not everyone needs fastlane.

> I need to install Fastlane every time when I start a CI job

You can publish your image on dockerhub.
