### ISSUE TITLE
Bundler is missing

### ISSUE THREAD

**Issue by berkerol** [react-native-community/docker-android#121]
Hi,

Ruby packages and `bundler` are removed in commit [95ba787a8efe9377bd2590459773567182cb0e6b](https://github.com/react-native-community/docker-android/commit/95ba787a8efe9377bd2590459773567182cb0e6b) but then Ruby packages are added in [e5f14ebd0639e8e03b012d8cf00c82b8da081e3f](https://github.com/react-native-community/docker-android/commit/e5f14ebd0639e8e03b012d8cf00c82b8da081e3f) and [07f8ec4802518459fa615fe8ae6549853dae366e](https://github.com/react-native-community/docker-android/commit/07f8ec4802518459fa615fe8ae6549853dae366e). We need `bundler` for our project and we have to install it manually in our Dockerfile for this reason. Are there any plans for adding `bundler` back?

**Comment by gengjiawen** [comment]
I will send a PR.
