### ISSUE TITLE
patch becomes not found in the latest version

### ISSUE THREAD

**Issue by mickeylam** [react-native-community/docker-android#126]
I am using "patch" to modify some react-native modules.

64 > ./patch/releasePatch.sh
65 ./patch/releasePatch.sh: 1: patch: not found
66 ./patch/releasePatch.sh: 2: patch: not found
67 ./patch/releasePatch.sh: 3: patch: not found
68 ./patch/releasePatch.sh: 4: patch: not found
69 ./patch/releasePatch.sh: 5: patch: not found
70 ./patch/releasePatch.sh: 6: patch: not found

I am not very familiar with the tools. But since the last update, I have got these in my CI. Can you check ? 
Thanks

**Comment by Jobeso** [comment]
I'm experiencing the same issue with the newest version. As a workaround I install patch manually in the set up step of the ci:
```bash
apt update
apt install -y patch
```

**Comment by gengjiawen** [comment]
added to latest version.
