### ISSUE TITLE
Error ndkVersion

### ISSUE THREAD

**Issue by DeVoresyah** [react-native-community/docker-android#128]
Hello,
I'm using this docker image in my GitLab ci/cd, but I don't know why I always got this error:
```
* What went wrong:
Execution failed for task ':app:stripReleaseDebugSymbols'.
> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 20.1.5948944
```

**Comment by siboulet** [comment]
The Docker image is still bundled with NDK 20.1.5948944.

You're probably using Gradle >3.5 that now expects some newer NDK: https://developer.android.com/studio/projects/install-ndk#default-ndk-per-agp

Try either downgrading to Gradle 3.5.0 in your your `build.gradle` file:

```
dependencies {
      classpath('com.android.tools.build:gradle:3.5.0')
...
```

Or try installing the missing NDK in your Docker container prior to building your your app by running:

> sdkmanager "ndk;21.0.6113669"
