### ISSUE TITLE
Why don't we use the adoptopenjdk base image?

### ISSUE THREAD

**Issue by eliaslecomte** [react-native-community/docker-android#131]
De Dockerfile currently starts from ubuntu:20.04.
Why would we not start from the Docker Hub supported adoptopenjdk images?

If I'm not mistaken this is the correct one: https://hub.docker.com/layers/adoptopenjdk/library/adoptopenjdk/8-jdk-hotspot/images/sha256-b44d8a1a7340966be6f8386653dd3de9b1bd007057e7cd28c954ab3e3ac21dfd?context=explore

**Comment by gengjiawen** [comment]
It will give us more control on OS choice and system software.
