### ISSUE TITLE
remove circle-ci

### ISSUE THREAD

**Issue by dulmandakh** [react-native-community/docker-android#135]
How about removing Circle CI and solely use GitHub Actions? @gengjiawen

**Comment by gengjiawen** [comment]
Maybe leave it for a while. CircleCI has remote ssh debug, which is really handy.

**Comment by dulmandakh** [comment]
I don't like the idea of publishing master as latest to docker hub. It'll break a lot of CI tasks due to breaking changes

**Comment by gengjiawen** [comment]
> I don't like the idea of publishing master as latest to docker hub. It'll break a lot of CI tasks due to breaking changes

Nope. You have misunderstanding of the latest tag. It's the common pattern.
