### ISSUE TITLE
How to update JDK version?

### ISSUE THREAD

**Issue by robrechtme** [react-native-community/docker-android#145]
Hi! In order to target SDK version 31 (Android 12), the project must be built with JDK 11 or higher (see [unrecognized Attribute name MODULE](https://stackoverflow.com/questions/68344424/unrecognized-attribute-name-module-class-com-sun-tools-javac-util-sharednametab)).

Is it possible to extend from this image and change the JDK version?

**Comment by jsamol** [comment]
It looks like [JDK 11 is already installed](https://github.com/react-native-community/docker-android/blob/v4.2/Dockerfile#L40). In your `Dockerfile`, you could try to overwrite [the `JAVA_HOME` env variable](https://github.com/react-native-community/docker-android/blob/v4.2/Dockerfile#L22) with a similar path, but for `openjdk-11`:
```
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
```

**Comment by robrechtme** [comment]
I will try that, thanks!
