### ISSUE TITLE
Dockerfile : Ruby & Bundler

### ISSUE THREAD

**Issue by Shankhara** [react-native-community/docker-android#157]
# Why is bundler installed ?

### Hi everyone,
I made some research before asking here, and I can't tell what does **ruby** and its **gem manager** here ?
https://github.com/react-native-community/docker-android/blob/48550c06005afa0bc8e1ce119db72e7c2ed0e69b/Dockerfile#L62
https://github.com/react-native-community/docker-android/blob/48550c06005afa0bc8e1ce119db72e7c2ed0e69b/Dockerfile#L89
Is it to allow a future Cocoapods installation ?

Hope I asked the question at the right place.
If not, please redirect me to the correct place :)

**Comment by Shankhara** [comment]
Found my answer :
https://github.com/react-native-community/discussions-and-proposals/discussions/411

**Comment by cortinico** [comment]
> I made some research before asking here, and I can't tell what does **ruby** and its **gem manager** here ?

As a side note: I believe we should not install ruby/bundler in this dockerfile as that's not effectively used for an Android image.
