### ISSUE TITLE
GitLab - NDK installation - Not enough space

### ISSUE THREAD

**Issue by Hajan39** [react-native-community/docker-android#158]
It looks like there is not enough space allowing docker to install NDK with a large package.

> License for package NDK (Side by side) 20.1.5948944 accepted.
Preparing "Install NDK (Side by side) 20.1.5948944 (revision: 20.1.5948944)".
Warning: An error occurred while preparing SDK package NDK (Side by side) 20.1.5948944: No space left on device.:
java.io.IOException: No space left on device

[full log can be found here](https://storage.googleapis.com/gitlab-gprd-artifacts/8e/7c/8e7ccbd95c1f0042ca5eecf9633728d675522d53c971c35e20beb37f2b132b5e/2021_12_16/1892758381/2051397666/job.log?response-content-type=text%2Fplain%3B%20charset%3Dutf-8&response-content-disposition=inline&GoogleAccessId=gitlab-object-storage-prd@gitlab-production.iam.gserviceaccount.com&Signature=xFehX84KgNy8qheeyA4g2SBJxHHckVo2b5p3YXBxYcCkMewsA3WWYlgN88ue%0A3AqUQkqNq1E%2FiEDZm%2FciSnTNNcuPFOeH6yqHKSuVYiVx%2FOewE54KYBM8fTjt%0AiIybFL8weGn11s9S4P4Vk6kmpbzxReqY1%2FZUZsTuSfBYGLjzID%2Facumj0034%0A%2F1SI30KEcjRStCR6Cjjiviemm1ap9tcLlKSYYuSuYO0qMtzqfw8XOvIwqDZ9%0ALfkBh3H7D8Lx6%2FonfP6%2B7o03ojVtJzbo9rnz5jo55Ayc9EZi5vq94dP9SmUX%0A5X1oFEwrGh%2BDKa6UyrHZw6ACaDiL72mFtc1zyI%2ByIg%3D%3D&Expires=1639664135)

**Comment by cortinico** [comment]
> Warning: An error occurred while preparing SDK package NDK (Side by side) 20.1.5948944: No space left on device.:
> java.io.IOException: No space left on device

This a problem with your underlying infrastructure. You should increase the space of the runner where you're loading this container

**Comment by Hajan39** [comment]
Maybe someone will help - I changed a runner for a tags:["gitlab-org-docker"] and it is working.
Than you

**Comment by backlands** [comment]
Apologies for reviving an old issue, but wanted to add some details for future developers!

This also worked for my team, for context this meant adding the following to the specific build job for your Android application:

```yml
  tags: ["gitlab-org-docker"]
```

**Comment by JeremyNohDriveco** [comment]
Thank you very much for the answer, indeed it fixes my problem! 😃

On the other hand the apk this build successfully but the apk is only 24MB instead of 33MB

So it installs well on the phone but impossible to open it 

Any ideas ?

Thanks in advance
