### ISSUE TITLE
update node to version 16

### ISSUE THREAD

**Issue by vdovhanych** [react-native-community/docker-android#172]
Since node version 16 is now LTS it would be a good thing to update the node version in the docker image.

**Comment by krudos** [comment]
currently in react native is define to use node 16 https://github.com/facebook/react-native/blob/main/.node-version
also i am trying to build a library using https://github.com/callstack/react-native-builder-bob and the minimum node version is 16

so i will appreciate if we merge this change

**Comment by cortinico** [comment]
> currently in react native is define to use node 16 [https://github.com/facebook/react-native/blob/main/.node-version](https://github.com/facebook/react-native/blob/main/.node-version?rgh-link-date=2022-11-21T15%3A00%3A39Z)

Please note that React Native currently has a **minimum** supported version of node being 14, and a suggested one being 16 (hence the `.node-version` file).

**Comment by krudos** [comment]
@cortinico does a refactor to use nvm make more sense?

**Comment by cortinico** [comment]
> @cortinico does a refactor to use nvm make more sense?

Nope. I think we should bump the min Node version to 16 and land the change you requested. But this requires a bit of a discussion on the React Native side
