### ISSUE TITLE
Shall we provide builds pinned to CircleCI manifest versions?

### ISSUE THREAD

**Issue by shamilovtim** [react-native-community/docker-android#181]
We currently use CircleCI's [macOS executor](https://circleci.com/docs/using-macos#supported-xcode-versions) which provides [native versions](https://circle-macos-docs.s3.amazonaws.com/image-manifest/v8770/index.html) of interpreters like node, ruby, etc pre-compiled as part of their macOS VM. They periodically bump these system dependencies in a way that makes sense and has never burned us so we continue to follow this pattern of versioning. This saves us time and money, however it comes with the downside that the docker CI Android env bifurcates if it pins different versions. If desirable, we can publish docker tags which pin to these CircleCI versions so that Android and iOS don't bifurcate on people's CI. 

Perhaps we could tag it according to the CircleCI nomenclature, which follows xcode versions? e.g. 14.0.0 vs. 13.4.1
If this would be better suited to a fork or anyone has any better suggestions please let me know!

Of particular interest to me would be to get node finally bumped out to v16 as well as to an exact patch version rather than generally `16.x`

**Comment by cortinico** [comment]
> This saves us time and money, however it comes with the downside that the docker CI Android env bifurcates if it pins different versions.

That's the whole point of a Docker container. You're not forced to use it, it's a convenience tool that ensures you get an environment with tools versioned as we tested them.

> Perhaps we could tag it according to the CircleCI nomenclature, which follows xcode versions? e.g. 14.0.0 vs. 13.4.1 If this would be better suited to a fork or anyone has any better suggestions please let me know!

I'm generally against this approach. This docker image is for building React Native Android Apps. It makes no assumptions on iOS and also it makes no assumption for the CI system you'll use it on.

We could do the same for any other CI system and we'll end up publishing multiple tags just to align on CI systems.
