### ISSUE TITLE
Release v6.0 on DockerHub

### ISSUE THREAD

**Issue by cortinico** [react-native-community/docker-android#184]
Opening this issue to discuss if we're fine bumping the Docker Image version to 6.x as there are a couple of breaking changes:
1. Using prebuilt BUCK instead of building from source
2. NDK to 23 for Gradle (this has breaking changes in terms of Environment variables)
3. Updated Ubuntu version to 22.04

cc @gengjiawen for confirmation

**Comment by kelset** [comment]
I think we should be good to do it, can't think of any reasons that might be blockers

**Comment by gengjiawen** [comment]
Go for it.

**Comment by cortinico** [comment]
Done 👍
