### ISSUE TITLE
How to setup Ruby version

### ISSUE THREAD

**Issue by JameDodgers** [react-native-community/docker-android#198]
When running `bundle install` I'm receiving the following error after upgrading to the newest RN version:

```
Your Ruby version is 2.7.0, but your Gemfile specified 2.7.6.
```

Is there any place where I can specify the Ruby version used by the image to be the same as specified in my `.ruby-version`?

**Comment by cortinico** [comment]
How is this related to this repo?

**Comment by JameDodgers** [comment]
Forgive me. It's probably not related, I started to get this error after trying to upgrade my react native project to the newest version where ruby version was set in Gemfile. I'm just trying to figure out how to handle it and seeking for some guidance.
