### ISSUE TITLE
CircleCI compatibility

### ISSUE THREAD

**Issue by charpeni** [react-native-community/docker-android#37]
Usually, CircleCI docker images are using `circleci` user instead of `root`. 

This means that `~/` will be referring to `/home/circleci` instead of `/root`. This won't be an issue when we're using `reactnativecommunity/react-native-android` image with only a step or multiple Android steps. Unfortunately, that may not work well with steps that are using other CircleCI's Docker images.

I'd recommend we implement a variant specific to CircleCI with the following settings: https://github.com/CircleCI-Public/example-images/blob/18035876801446bf04a58a957692ff04cd47b256/android/Dockerfile#L46-L99

Thoughts?

**Comment by gengjiawen** [comment]
In my practice with docker, root can fit in most cases.
I don't see why we have to add a new user.

So maybe used this image as an base image if you want to tweak a few things.
