### ISSUE TITLE
How does this compare to the CircleCI provided images?

### ISSUE THREAD

**Issue by matt-oakes** [react-native-community/docker-android#38]
How does this Docker image compare to the ones provided by CircleCI? What is included in this image which is missing from the CircleCI ones?

* [Example Dockerfile](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/android/images/api-23-node8-alpha/Dockerfile)
* [Full list of supported tags](https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/android/images)

I am currently using your Docker image for [react-native-circleci-orb](https://github.com/react-native-community/react-native-circleci-orb), however, I would ideally like to allow users of the Orb to customise the Android tools version they want to use. The CircleCI images would allow this through different tags, but this image currently would not.

If this image provides something that the CircleCI ones don't then we can attempt to add tag support here. If, however, they are similar then I might switch to use the CircleCI ones.

**Comment by dulmandakh** [comment]
It includes Buck, Android SDK and Android NDK, which requires less setup and less resource on CircleCI.

**Comment by matt-oakes** [comment]
Ok, that makes sense. I'll need to look into the best way to support multiple versions of the SDK easily while still keeping those dependencies 👍

**Comment by dulmandakh** [comment]
You can use it as a base and add other SDKs.

**Comment by gengjiawen** [comment]
> Ok, that makes sense. I'll need to look into the best way to support multiple versions of the SDK easily while still keeping those dependencies 👍

It's also smaller than circle ci image (2.7GB vs 2GB). See https://microbadger.com/images/circleci/android:api-28-ndk-r17b.

Also very easy to customize if you want to add additional function.
