### ISSUE TITLE
How to use the Docker?

### ISSUE THREAD

**Issue by tal987** [react-native-community/docker-android#60]
# Question

Hi, I was wondering first if the docker is working? and if its support react native 0.60.5?
Second, How should I install the docker and use it, the readMe file doesn't explain enough...

Thank you

**Comment by gengjiawen** [comment]
> if its support react native 0.60.5?

I have not tested it, but it should work. It's used in the main repo.

> How should I install the docker and use it, the readMe file doesn't explain enough...

Depend on your needs, you want build the source or just a plain react native app.

**Comment by tal987** [comment]
@gengjiawen I need the docker for building the app and then upload the build file (apk) to s3...
In this case how should I install and use the docker? The docker file in this git is match to my needs?

Thank you

**Comment by gengjiawen** [comment]
You can view the sample here: https://github.com/react-native-community/ci-sample. Upload to s3 you can use curl command or write a node script.

**Comment by tal987** [comment]
@gengjiawen i don’t understand how to use it... the readMe file doesn’t explain anything. What file should I look for, how to use it?

**Comment by gengjiawen** [comment]
Looks like you are not familiar with CI system. Check this for start:

https://github.com/react-native-community/ci-sample/blob/da0ef71f215b6bff21c308df28815eb9d44489a3/.circleci/config.yml#L11

**Comment by tal987** [comment]
@gengjiawen I know this commands in the ci. I don’t understand how does it use with docker what exactly is this file doing? How do I actually run it? Anyway I would like to use with TeamCity for runny the ci is that possible?

**Comment by gengjiawen** [comment]
That's the problem you need to solve. I am not familiar with Teamcity.

**Comment by tal987** [comment]
@gengjiawen That’s why I need the docker. Because in TeamCity there is a plug for dockers. So your docker can build environment for react native and can build the app?

**Comment by gengjiawen** [comment]
yeap.
