### ISSUE TITLE
Source repo on docker hub is wrong

### ISSUE THREAD

**Issue by compojoom** [react-native-community/docker-android#68]
On the docker hub page here: https://hub.docker.com/r/reactnativecommunity/react-native-android/ the source repository is set to gengjiawen/docker-android, but gengjiawen/docker-android is a fork of this repository. 

We need to update the listing to point to this repo.

**Comment by gengjiawen** [comment]
Yeap. I realize that too. But dockehub has not provide a way to change it.

**Comment by gengjiawen** [comment]
Aha, I find a way to delete it. Thanks.

**Comment by compojoom** [comment]
I see that you've deleted it there now. 
Can we have a link to this repo there now?

**Comment by gengjiawen** [comment]
Looks like it need organisation admin to do that. I put the repo in README for now.
