### ISSUE TITLE
Side-by-side NDK

### ISSUE THREAD

**Issue by EternalDeiwos** [react-native-community/docker-android#69]
# Feature Request

Use `sdkmanager` to install ndk ("side-by-side") instead of doing so manually.

## Why it is needed

This was recently added by Google to enable multiple versions of the NDK to be installed at the same time. The result is that various gradle plugins (in my case, most notable being mozilla/rust-android-gradle) have changed to expect the NDK to be installed side-by-side.

## Possible implementation

For example adding `"ndk;${SDK_NDK_VERSION}"` to the `sdkmanager` installation list will cause the specified version to be installed (IIRC you need the full version string).

**Comment by dulmandakh** [comment]
@EternalDeiwos great idea. Could you please create a PR, I would happy to review it. Thanks
