### ISSUE TITLE
Choose organization name in dockerhub

### ISSUE THREAD

**Issue by gengjiawen** [react-native-community/docker-android#7]
dockerhub not allow `-`, only lower letter.

**Comment by gengjiawen** [comment]
name like `reactnativecommunity` looks too long and hard to read.

**Comment by n1ru4l** [comment]
what about `rncommunity`

**Comment by flexbox** [comment]
Agreed that `reactnativecommunity` is too long.
But on the other hand, without context `rncommunity` doesn't mean anything.

In the react ecosystem we are writing declarative and explicit code.
Following this principe `reactnativecommunity` seams a better choice for discoverability/googling

**Comment by gengjiawen** [comment]
Settle with reactnativecommunity.
