### ISSUE TITLE
Latest image missing bundler

### ISSUE THREAD

**Issue by SRandazzo** [react-native-community/docker-android#75]
# Bug report

Since the most recent docker image has been published, my android builds have been failing due to `bundle: command not found`

## Summary

Builds error out on `bundle: command not found`. I was able to confirm that rolling back to a fixed version: `reactnativecommunity/react-native-android:2020-4-1` resolves the issue for me.

## Steps to reproduce

Attempt to use the latest image on CircleCI with a bundle step:
(ie: `bundle install`) and it fails with `bundle: command not found`

Thanks!

**Comment by gengjiawen** [comment]
Fixed in https://github.com/react-native-community/docker-android/pull/76.

**Comment by SRandazzo** [comment]
thanks!
