### ISSUE TITLE
release process

### ISSUE THREAD

**Issue by dulmandakh** [react-native-community/docker-android#84]
Let's adopt release process and have release notes for the image builds. Easiest would be to use GitHub releases and have release notes for each release. It would be useful for users when deciding which version to use, for example in the future we would remove NDK 20 and offer NDK 21, so release notes will be essential for breaking changes.

And let's not publish master to the Docker registry, because we might have some changes that does not affect the image, for example dropping Circle CI etc.

**Comment by dulmandakh** [comment]
Maybe we shouldn't publish latest tag, so that developers must use specific version of the image. In that case we can publish an image with NDK 21, and mark as breaking change.

**Comment by gengjiawen** [comment]
> Maybe we shouldn't publish latest tag, so that developers must use specific version of the image

Since it's more like common convention. Not a good idea not pushing it.

**Comment by dulmandakh** [comment]
And how about using GitHub releases? Let’s not publish master as is.

**Comment by dulmandakh** [comment]
https://github.com/react-native-community/docker-android/commit/5d68d7d3117d0069498628141f4c21a9fec7af9b will build and publish Docker image on release
