### ISSUE TITLE
release a new version

### ISSUE THREAD

**Issue by dulmandakh** [react-native-community/docker-android#86]
@gengjiawen please release a new version and check if GitHub Action is working as expected, also release an image with version tag so I can use it on React Native CI. Thanks

**Comment by gengjiawen** [comment]
https://github.com/react-native-community/docker-android/runs/1278362080?check_suite_focus=true

**Comment by gengjiawen** [comment]
![image](https://user-images.githubusercontent.com/3759816/96527479-baa84280-12b2-11eb-84cb-494620a8998b.png)

**Comment by gengjiawen** [comment]
Looks the `publish.yml` is not valid, can you give a try on your personal fork and fix related issue ?

**Comment by dulmandakh** [comment]
> Looks the publish.yml is not valid, can you give a try on your personal fork and fix related issue ?
> 
> 

I’m doing exactly that. And will create a PR once complete
